### ISSUE TITLE
Add leapt

### ISSUE THREAD

**Issue by colejohnson66** [LibreOffice/dictionaries#2]
In English (at least en_us), "leapt" is the correct past tense form of "leap" (contrary to popular belief, it's not "lept").

**Comment by equaeghe** [comment]
This is not the place to report modifications to dictionary files, as it is just a repository where various dictionaries are collected. For reporting issues with en_US, see

http://wordlist.aspell.net/

Regarding your request, see

http://app.aspell.net/lookup?dict=en_US;words=leapt

I'd suggest closing this issue here, as no action will or can be taken based on it.
