### ISSUE TITLE
Missing 'reputational' from en

### ISSUE THREAD

**Issue by OJFord** [LibreOffice/dictionaries#24]
`reputational` does not match in `en_GB`.

I don't know what `/MS` and `/MO` mean, but I noticed that differed on the prefix `reputation` between `en_US` & `en_GB`, so I tried the former too wondering if perhaps it was an Americani(z)m I was unaware of, but that didn't accept it either.

It's unqualified as such or as slang or anything on [Wiktionary](https://en.wiktionary.org/wiki/reputational), and in fact Collins describes it as 'formal'.

**Comment by marcoagpinto** [comment]
I released the British dictionary yesterday or the day before, so now it will take around a month to make another update.

The flags used vary from the different spellers because the rules are in the .AFF file.

In GB, the flag "S" adds plural "+s", the flag "M" adds possessive "+'s" and the flag "O" adds "+al" (reputation+al).
