### ISSUE TITLE
'voting' considered not a word, returned suggestions: 'shooting', 'looting', 'rioting' 

### ISSUE THREAD

**Issue by tuggerfub** [LibreOffice/dictionaries#27]
I've been referred to this git by @[phillipseamore ](https://github.com/phillipseamore)of the [Hunspell ](https://github.com/hunspell/hunspell/issues/697)git regarding this particular issue: 
> https://www.youtube.com/watch?v=diBuFOK6Uhg
> 
> For some reason your spellcheck dictionary returns specific corrections for the word 'voting'; "shooting", "looting" and "rioting".
I have also posted an inquiry in the LibreOffice IRC chat and the libreoffice.org question board without response. 
![wtflibreoffice](https://user-images.githubusercontent.com/31835864/96322312-91539200-0fe6-11eb-9c37-90a8c7505463.jpg)

I would like someone to provide a rational explanation as to how this spellcheck was produced. My word editing software's _spellchecker_ is the last place I expected to find polemic bile.

**Comment by tuggerfub** [comment]
I'm wondering if the gentleman who added these words and their specific values to the en_CA dictionary would have a comment, given they've devoted the bulk of their personal website to a professed neonazi (their words) who sells immortality magnet rings.

**Comment by marcoagpinto** [comment]
@tuggerfub 

Hello!

Are you referring to me since you mentioned magnetic rings?

I am only adding words to the British dictionary.

For the other variants you must contact Kevin Atkinson.

Anyway, for a word to accept possessive, the possessive must be in the wordlist.

So, if the speller only has:
voting
it will report a typo if you write
voting's

For a year or so that I have been adding possessives to words in GB, but it is a lifetime task.

I hope this helps.

**Comment by marcoagpinto** [comment]
Anyway, it was also missing in the GB speller, so I have just added it:
62551) voting (+plural +'s)

It will be available on 1-NOV (V2.90 of the GB dictionary).
