### ISSUE TITLE
Words hyphenated incorrected

### ISSUE THREAD

**Issue by paulvonhippel** [LibreOffice/dictionaries#44]
SINGING, WHIPLASH, and FIZZES are two-syllable words but are listed with one syllable. Why?

**Comment by cloph** [comment]
small remark: hyphenation is not so much about syllables, but about typography, so combinations might be blacklisted from automatic hyphenation because splitting a word would be considered bad style from a typesetting POV/when splitting a word impacts comprehension, or leaves too few letters at end of line or start of the new line.
And of course dictionaries as used by LibreOffice don't list every possible word, but are using patterns. you can always add your own definitions or place soft-hyphens manually to allow line-breaks in words that the automatic hyphenation doesn't consider.

**Comment by paulvonhippel** [comment]
Yeah, I was thinking about this. From a hyphenation point of view, it's OK
if you decide there are some words that you won't break, especially if
they're short. What I'm really looking for is a syllabification library,
but I tried the eng_syl library and it's not entirely accurate, so I'm
using hyphenation libraries too.

Best,
Paul
